/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_yezhou_fftw_FFTW */

#ifndef _Included_me_yezhou_fftw_FFTW
#define _Included_me_yezhou_fftw_FFTW
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_yezhou_fftw_FFTW
 * Method:    fftwInit
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_yezhou_fftw_FFTW_fftwInit
  (JNIEnv *, jclass);

/*
 * Class:     me_yezhou_fftw_FFTW
 * Method:    fftwDft1d
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_me_yezhou_fftw_FFTW_fftwDft1d
  (JNIEnv *, jclass);

/*
 * Class:     me_yezhou_fftw_FFTW
 * Method:    fftwDftR2c1d
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_me_yezhou_fftw_FFTW_fftwDftR2c1d
  (JNIEnv *, jclass);

/*
 * Class:     me_yezhou_fftw_FFTW
 * Method:    fftwfDftR2c1d
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_me_yezhou_fftw_FFTW_fftwfDftR2c1d
  (JNIEnv *, jclass);

/*
 * Class:     me_yezhou_fftw_FFTW
 * Method:    fftwfDftR2c1dThread
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_me_yezhou_fftw_FFTW_fftwfDftR2c1dThread
  (JNIEnv *, jclass);

/*
 * Class:     me_yezhou_fftw_FFTW
 * Method:    fftwfDftR2c1dThreadMeasure
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_me_yezhou_fftw_FFTW_fftwfDftR2c1dThreadMeasure
  (JNIEnv *, jclass);

/*
 * Class:     me_yezhou_fftw_FFTW
 * Method:    fftwDft2d
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_me_yezhou_fftw_FFTW_fftwDft2d
  (JNIEnv *, jclass);

/*
 * Class:     me_yezhou_fftw_FFTW
 * Method:    fftwDftR2c2d
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_me_yezhou_fftw_FFTW_fftwDftR2c2d
  (JNIEnv *, jclass);

/*
 * Class:     me_yezhou_fftw_FFTW
 * Method:    fftwfDftR2c2d
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_me_yezhou_fftw_FFTW_fftwfDftR2c2d
  (JNIEnv *, jclass);

/*
 * Class:     me_yezhou_fftw_FFTW
 * Method:    fftwfDftR2c2dThread
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_me_yezhou_fftw_FFTW_fftwfDftR2c2dThread
  (JNIEnv *, jclass);

/*
 * Class:     me_yezhou_fftw_FFTW
 * Method:    fftwfDftR2c2dThreadMeasure
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_me_yezhou_fftw_FFTW_fftwfDftR2c2dThreadMeasure
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
